config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # rubocop:todo Metrics/BlockLength
  root 'welcome#index'

  get 'image/:id/serve', to: 'images#serve', as: :serve_image
  get 'e-booklet', to: 'welcome#serve_booklet', as: :serve_booklet

  resources :gallery_photos, only: :index

  resources :event_previews, only: :index

  devise_scope :user do
    get '/sign_up' => 'users/registrations#new', as: :new_user_registration

    get '/login' => 'users/sessions#new', as: :new_user_session
    post '/login' => 'users/sessions#create', as: :user_session
    delete '/logout' => 'users/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users,
             skip: %i[sessions],
             controllers: {
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               confirmations: 'users/confirmations',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }

  resources :events, only: %i[index show], param: :year do
    get 'load_photos',
        to: 'events#load_photos',
        as: :load_photos,
        constraints: ->(req) { req.format == :js }
  end

  get '/ticket/claim', to: 'tickets#claim', as: 'claim_ticket'
  post '/tickets/synchronize', to: 'tickets#synchronize'

  get '/sold_out_night', to: 'welcome#sold_out_night', as: 'sold_out_night'
  get '/sold_out_matinee',
      to: 'welcome#sold_out_matinee', as: 'sold_out_matinee'
  get '/buy_special', to: 'welcome#buy_special', as: 'buy_special'
  get '/donation', to: 'welcome#donation', as: 'donation'

  namespace :admin do
    root 'admin#index'

    resources :users, except: %i[new create]
    resources :frequently_asked_questions, except: :show
    resources :testimonies

    resources :events, param: 'year' do
      resources :sponsors
      resources :gallery_photos, only: %i[index new create destroy]
      resources :event_previews
    end

    resources :tickets, only: %i[create new index show destroy]
    get '/ticket/claim', to: 'tickets#claim', as: 'claim_ticket'
    post '/ticket/claim', to: 'tickets#redeem', as: nil
    post '/ticket/confirmation_email/:id',
         to: 'tickets#send_confirmation_email', as: 'ticket_email_confirmation'
    post '/tickets/clear_mock_tickets',
         to: 'tickets#clear_mock_tickets', as: 'clear_mock_tickets'

    resources :subscribers, only: %i[index destroy]
    get 'subscribers/write_email',
        to: 'subscribers#write_email', as: :write_email
    post 'subscribers/send_email', to: 'subscribers#send_email', as: :send_email
    get 'subscribers/confirm_email_sent',
        to: 'subscribers#confirm_email_sent', as: :confirm_email_sent
    get 'subscribers/sync_with_customer',
        to: 'subscribers#sync_with_customer', as: :sync_with_customer
  end

  get '/unsubscribe', to: 'admin/subscribers#unsubscribe', as: :unsubscribe
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_one :logo, as: :imageable, dependent: :destroy, class_name: 'Image'
  accepts_nested_attributes_for :logo,
                                reject_if: :all_blank, allow_destroy: true

  has_one :event_info,
          dependent: :destroy,
          foreign_key: :year,
          primary_key: :year,
          inverse_of: :event
  accepts_nested_attributes_for :event_info

  has_many :sponsors,
           dependent: :destroy,
           foreign_key: :year,
           primary_key: :year,
           inverse_of: :event

  has_many :gallery_photos,
           dependent: :destroy,
           foreign_key: :year,
           primary_key: :year,
           inverse_of: :event

  has_many :event_previews,
           dependent: :destroy,
           foreign_key: :year,
           primary_key: :year,
           inverse_of: :event

  validates :year, :title, :overview, presence: true
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

module Admin
  class EventsController < ApplicationController
    include EventsHelper

    before_action :ensure_admin
    before_action :set_event, only: %i[show edit update destroy]

    def index
      get_all_event
    end

    def show; end

    def new
      @event = Event.new
      @event.build_event_info
      @event.build_logo
    end

    def edit
      @event.build_logo if @event.logo.nil?
    end

    def create
      @event = Event.new(event_params)

      if @event.save
        redirect_to admin_event_path(@event.year),
                    notice: 'Event was successfully created.'
      else
        render :new
      end
    end

    def update
      if @event.update(event_params)
        redirect_to admin_event_path(@event.year),
                    notice: 'Event was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @event.destroy
      redirect_to admin_events_url, notice: 'Event was successfully destroyed.'
    end

    private

    def ensure_admin
      super || return
    end

    def event_params
      params.require(:event).permit(
        :title,
        :subtitle,
        :overview,
        :year,
        :logo,
        event_info_attributes: %i[id synopsis description video_link],
        logo_attributes: %i[id file _destroy]
      )
        .tap { |event_params| event_params.require(:event_info_attributes) }
    end
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  include EventsHelper
  include UrlHelper

  def index
    get_all_event
  end

  def show
    set_event
    @gallery_photos = @event.gallery_photos.limit(8)
    @more_photos = @event.gallery_photos.count > 8
    @event_previews = @event.event_previews
  end

  def load_photos
    year = current_year
    year = params[:year].to_i if params[:year]
    year = params[:event_year].to_i if params[:event_year]

    offset = params[:offset].nil? ? 0 : params[:offset].to_i
    take = params[:take].nil? ? 8 : params[:take].to_i

    event = Event.find_by(year: year)

    @gallery_photos = event.gallery_photos.offset(offset).limit(take)
    @more_photos = (offset + take) < event.gallery_photos.count

    respond_to(&:js)
  end # rubocop:todo Metrics/AbcSize
end

app/helpers/admin/events_helper.rb
# frozen_string_literal: true

module Admin
  module EventsHelper
    def set_event
      year = params[:year] || params[:event_year]
      @event =
        begin
          Event.find_by!(year: year)
        rescue StandardError
          not_found
        end
    end

    def get_all_event
      @events = Event.all.order(year: :desc)
    end # rubocop:todo Naming/AccessorMethodName
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def set_event
    not_found && return if params[:year].to_i >= current_year
    @event =
      begin
        Event.find_by!(year: params[:year])
      rescue StandardError
        not_found
      end
  end

  def get_all_event
    @events = Event.where('year < ?', current_year).order(year: :desc)
  end # rubocop:todo Naming/AccessorMethodName
end

app/views/admin/events/_form.html.erb
<%= form_with(model: event, local: true, url: target_url, remote: true, html: { id: 'event-info-form' } ) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-fields">

    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :year, "Year" %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.number_field :year, min: 2008, max: 2099, required: true %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :title, "Title" %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.text_field :title, required: true %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :subtitle, "Subtitle" %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.text_field :subtitle %> <br>
      </div>
    </div>
    <%= render "admin/image/image_form", form: form, field: :logo %>
    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :overview, "Short Description" %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.text_area :overview, required: true %>
      </div>
    </div>
    <%= form.fields_for :event_info do |event_info_form| %>
      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-2 col-md-12 field-key">
          <%= event_info_form.label :description, "Full Description" %>
        </div>
        <div class="col-lg-10 col-md-12 field-value">
          <%= event_info_form.hidden_field :description, required: true %>
          <div id="editor-container">
          </div>
          <br>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-2 col-md-12 field-key">
          <%= event_info_form.label :synopsis %>
        </div>
        <div class="col-lg-10 col-md-12 field-value">
          <%= event_info_form.text_area :synopsis, required: true %>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-2 col-md-12 field-key">
          <%= event_info_form.label :video_link %>
        </div>
        <div class="col-lg-10 col-md-12 field-value">
          <%= event_info_form.text_field :video_link %>
        </div>
      </div>
    <% end %>
    <div class="row">
      <div class="col-lg-12">
        <%= form.submit 'Submit', class: "submit-button" %>      
      </div>
    </div>
  </div>
  
  <script>
    var toolbarOptions = {
      container: [
        ['bold', 'italic', 'underline'],
        ['link'],
      ],
      handlers: {
        // UI improvements. The original had an ugly-looking input field
        'link': function(value) {
          if (value) {
            var href = prompt('Enter the URL');
            this.quill.format('link', href);
          } else {
            this.quill.format('link', false);
          }
        }
      }
    }

    // Initialises the div with id='editor-container' to be a quill editor, with toolbarOptions specified above
    var quill = new Quill('#editor-container', {
      modules: {
        toolbar: toolbarOptions
      },
      placeholder: 'Insert full description here...',
      theme: 'snow'
    });

    /* If we are editing an event, this code will retrieve the html text from the database that is loaded 
       into the form, and inject it to the quill editor.

       During runtime, the code `event_info_form.hidden_field :description, required: true` gets resolved 
       to have `id="event_event_info_attributes_description"`. For more details, you can read at
       `https://github.com/nuansa-cp/gapura/pull/84#discussion_r302797872`.
    */
    var postContentInput = document.querySelector('#event_event_info_attributes_description');
    quill.root.innerHTML = postContentInput.value

    /* Copied from StackOverflow, but this is the piece of code that allows any changes in html text
       from the quill editor to be injected into the hidden_field: 
       event_info_form.hidden_field :description, required: true
    */ 
    quill.on('text-change', function() {
      $("#event_event_info_attributes_description").val(quill.root.innerHTML);
    });
  </script>
<% end %>

app/views/admin/events/edit.html.erb
<% provide(:custom_css, 'admin/events/form') %>

<section class="section-container">
  <div class="row">
    <div class="title">
      Edit Event
    </div>
    <div class="content">
      <div id="admin-form">
        <%= render 'form', event: @event, target_url: admin_event_path(@event.year) %>
      </div>
      
      <br><br>
      
      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-3 col-md-4 col-xs-4">
          <%= button_to('Sponsors', admin_event_sponsors_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-4">
          <%= button_to('Gallery', admin_event_gallery_photos_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-3 col-md-4 col-xs-4">
          <%= button_to("Previews", admin_event_event_previews_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-3 col-md-12 col-xs-12">
          <%= button_to("Back", admin_events_path, method: "get", class: "btn btn-info") %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/events/index.html.erb
<% provide(:custom_css, 'admin/events/index') %>

<section id="admin-events-index" class="section-container">
  <div class="row">
    <div class="title">
      Event List
    </div>
    <div class="content">
      <% @events.each do |event| %>
        <div class="row info-fields">
          <div class="col-lg-12"></div>
          <div class="col-lg-1 col-md-12 col-xs-12 info-item"><%= event.year %></div>
          <div class="col-lg-2 col-md-12 col-xs-12 info-item"><%= event.title %></div>
          <div class="col-lg-3 col-md-12 col-xs-12 info-item"><%= event.subtitle %></div>

          <div class="col-lg-1 col-md-4 col-xs-4 info-item">
            <%= button_to("Show", admin_event_path(event.year), method: "get", class: "btn btn-info") %>
          </div>

          <div class="col-lg-1 col-md-4 col-xs-4 info-item">
            <%= button_to("Edit", edit_admin_event_path(event.year), method: "get", class: "btn btn-info") %>
          </div>
          
          <div class="col-lg-1 col-md-4 col-xs-4 info-item">
            <%= button_to("Previews", admin_event_event_previews_path(event.year), method: "get", class: "btn btn-info") %>
          </div>
          
          <div class="col-lg-1 col-md-4 col-xs-4 info-item">
            <%= button_to("Sponsors", admin_event_sponsors_path(event.year), method: "get", class: "btn btn-info") %>
          </div>

          <div class="col-lg-1 col-md-4 col-xs-4 info-item">
            <%= button_to("Gallery", admin_event_gallery_photos_path(event.year), method: "get", class: "btn btn-info") %>
          </div>

          <div class="col-lg-1 col-md-4 col-xs-4 info-item">
            <%= button_to("Delete", admin_event_path(event.year), method: :delete, class: "btn btn-info",
                  data: {confirm: "Do you want to delete this event?"}) %>
          </div>
        </div>
      <% end %>

      <br><br>

      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-6">
          <%= button_to("Back", admin_root_path, method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-6">
          <%= button_to("Add Past Event", new_admin_event_path, method: "get", class: "btn btn-info") %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/events/new.html.erb
<% provide(:custom_css, 'admin/events/form') %>

<section class="section-container">
  <div class="row">
    <div class="title">
      New Event
    </div>
    <div class="content">
      <div id="admin-form">
        <%= render 'form', event: @event, target_url: admin_events_path %>
      </div>

      <br><br>
      
      <div class="row">
        <div class="col-lg-12">
          <%= button_to("Back", admin_events_path, method: "get", class: "btn btn-info") %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/events/show.html.erb
<% provide(:custom_css, 'admin/events/show') %>

<section id="admin-show" class="section-container">
  <div class="row">
    <div class="title">
      Event Show
    </div>
    <div class="content">
      <div class="info-fields">
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Year</div>
          <div class="col-lg-10 col-md-12 field-value"><%= @event.year %></div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Title</div>
          <div class="col-lg-10 col-md-12 field-value"><%= @event.title %></div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Subtitle</div>
          <div class="col-lg-10 col-md-12 field-value"><%= @event.subtitle %></div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Logo</div>
          <div class="col-lg-10 col-md-12 field-value">
            <%= @event.logo.present? ? image_tag(serve_image_path(@event.logo), height: '100px') : 'NO LOGO' %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Overview</div>
          <div class="col-lg-10 col-md-12 field-value"><%= @event.overview %></div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Description</div>
          <div class="col-lg-10 col-md-12 field-value">
            <%= raw sanitize @event.event_info.description, tags: %w(strong em a u br), attributes: %w(href) %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Synopsis</div>
          <div class="col-lg-10 col-md-12 field-value"><%= @event.event_info.synopsis %></div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Video Link</div>
          <div class="col-lg-10 col-md-12 field-value"><%= @event.event_info.video_link %></div>
        </div>
      </div>
      
      <br><br>

      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-2 col-md-4 col-xs-4">
          <%= button_to('Sponsors', admin_event_sponsors_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-2 col-md-4 col-xs-4">
          <%= button_to('Gallery', admin_event_gallery_photos_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-2 col-md-4 col-xs-4">
          <%= button_to("Previews", admin_event_event_previews_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-2 col-md-4 col-xs-4">
          <%= button_to("Edit", edit_admin_event_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-2 col-md-4 col-xs-4">
          <%= button_to("Delete", admin_event_path(@event.year), method: :delete, class: "btn btn-info",
              data: {confirm: "Do you want to delete this event?"}) %>
        </div>
        <div class="col-lg-2 col-md-4 col-xs-4">
          <%= button_to("Back", admin_events_path, method: "get", class: "btn btn-info") %>
        </div>
      </div>
    </div>
  </div>
</section>