config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # rubocop:todo Metrics/BlockLength
  root 'welcome#index'

  get 'image/:id/serve', to: 'images#serve', as: :serve_image
  get 'e-booklet', to: 'welcome#serve_booklet', as: :serve_booklet

  resources :gallery_photos, only: :index

  resources :event_previews, only: :index

  devise_scope :user do
    get '/sign_up' => 'users/registrations#new', as: :new_user_registration

    get '/login' => 'users/sessions#new', as: :new_user_session
    post '/login' => 'users/sessions#create', as: :user_session
    delete '/logout' => 'users/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users,
             skip: %i[sessions],
             controllers: {
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               confirmations: 'users/confirmations',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }

  resources :events, only: %i[index show], param: :year do
    get 'load_photos',
        to: 'events#load_photos',
        as: :load_photos,
        constraints: ->(req) { req.format == :js }
  end

  get '/ticket/claim', to: 'tickets#claim', as: 'claim_ticket'
  post '/tickets/synchronize', to: 'tickets#synchronize'

  get '/sold_out_night', to: 'welcome#sold_out_night', as: 'sold_out_night'
  get '/sold_out_matinee',
      to: 'welcome#sold_out_matinee', as: 'sold_out_matinee'
  get '/buy_special', to: 'welcome#buy_special', as: 'buy_special'
  get '/donation', to: 'welcome#donation', as: 'donation'

  namespace :admin do
    root 'admin#index'

    resources :users, except: %i[new create]
    resources :frequently_asked_questions, except: :show
    resources :testimonies

    resources :events, param: 'year' do
      resources :sponsors
      resources :gallery_photos, only: %i[index new create destroy]
      resources :event_previews
    end

    resources :tickets, only: %i[create new index show destroy]
    get '/ticket/claim', to: 'tickets#claim', as: 'claim_ticket'
    post '/ticket/claim', to: 'tickets#redeem', as: nil
    post '/ticket/confirmation_email/:id',
         to: 'tickets#send_confirmation_email', as: 'ticket_email_confirmation'
    post '/tickets/clear_mock_tickets',
         to: 'tickets#clear_mock_tickets', as: 'clear_mock_tickets'

    resources :subscribers, only: %i[index destroy]
    get 'subscribers/write_email',
        to: 'subscribers#write_email', as: :write_email
    post 'subscribers/send_email', to: 'subscribers#send_email', as: :send_email
    get 'subscribers/confirm_email_sent',
        to: 'subscribers#confirm_email_sent', as: :confirm_email_sent
    get 'subscribers/sync_with_customer',
        to: 'subscribers#sync_with_customer', as: :sync_with_customer
  end

  get '/unsubscribe', to: 'admin/subscribers#unsubscribe', as: :unsubscribe
end

app/models/sponsor.rb
# frozen_string_literal: true

class Sponsor < ApplicationRecord
  self.inheritance_column = 'inheritance_type'

  has_one :logo, as: :imageable, dependent: :destroy, class_name: 'Image'
  belongs_to :event, foreign_key: :year, primary_key: :year

  accepts_nested_attributes_for :logo,
                                reject_if: :all_blank, allow_destroy: true

  validates :type, :name, presence: true
end

app/controllers/admin/sponsors_controller.rb
# frozen_string_literal: true

module Admin
  class SponsorsController < ApplicationController
    include EventsHelper
    include UrlHelper

    before_action :ensure_admin
    before_action :set_event
    before_action :set_sponsor, only: %i[show edit update destroy]

    def index
      @sponsors = @event.sponsors.order(:type)
    end

    def show; end

    def new
      @sponsor = @event.sponsors.build
      @sponsor.build_logo
    end

    def edit
      @sponsor.build_logo if @sponsor.logo.nil?
    end

    def create
      @sponsor = @event.sponsors.build(sponsor_params)

      if @sponsor.save
        redirect_to admin_event_sponsor_url(@event.year, @sponsor),
                    notice: 'Sponsor was successfully created.'
      else
        render :new
      end
    end

    def update
      if @sponsor.update(sponsor_params)
        redirect_to admin_event_sponsor_url(@event.year, @sponsor),
                    notice: 'Sponsor was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @sponsor.destroy
      redirect_to admin_event_sponsors_path(@event.year),
                  notice: 'Sponsor was successfully destroyed.'
    end

    private

    def set_sponsor
      @sponsor = @event.sponsors.find(params[:id])
    end

    def sponsor_params
      params.require(:sponsor).permit(
        :type,
        :name,
        :link,
        logo_attributes: %i[id file _destroy]
      )
    end
  end
end

app/helpers/admin/sponsors_helper.rb
# frozen_string_literal: true

module Admin::SponsorsHelper; end

app/views/admin/sponsors/_form.html.erb
<%= form_with(model: sponsor, local: true, url: target_url) do |form| %>
  <% if sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% sponsor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-fields">
    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :type %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.text_field :type, required: true %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :name %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.text_field :name, required: true %>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :link %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.text_field :link %>
      </div>
    </div>
    <%= render "admin/image/image_form", form: form, field: :logo %>
    <div class="row">
      <div class="col-lg-12">
        <%= form.submit 'Submit', class: "submit-button" %>      
      </div>
    </div>
  </div>
<% end %>

app/views/admin/sponsors/edit.html.erb
<section id="admin-form" class="section-container">
  <div class="row">
    <div class="title">
      Edit Sponsor for NUANSA <%= @event.year %>
    </div>
    <div class="content">
      <%= render 'form', sponsor: @sponsor, target_url: admin_event_sponsor_path %>

      <br><br>
      
      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-3">
          <%= button_to("Event Menu", admin_events_path, method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-3">
          <%= button_to("Show Event", admin_event_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-3">
          <%= button_to('Sponsors', admin_event_sponsors_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-3">
          <%= button_to('Preview', admin_event_sponsor_path(@event.year, @sponsor), method: "get", class: "btn btn-info") %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/sponsors/index.html.erb
<% provide(:custom_css, 'admin/sponsors/index') %>

<section id="admin-sponsors-index" class="section-container">
  <div class="row">
    <div class="title">
      Sponsors for NUANSA <%= @event.year %>
    </div>
    <div class="content">
      <div class="col-lg-12">
        <div class="row">
          <div class="col-md-12"></div>
          <div class="col-md-6">
            <%= button_to("Back", admin_event_path(@event.year), method: "get", class: "btn btn-info") %>
          </div>
          <div class="col-md-6">
            <%= button_to("Add Sponsor", new_admin_event_sponsor_path(@event.year) , method: "get", class: "btn btn-info")%>
          </div>
        </div>

        <br><br>

        <div class="row">
          <div class="col-lg-12"></div>
          <% @sponsors.each do |sponsor| %>
            <div class="col-lg-3 col-md-4 col-xs-12">
              <div class="image-box-4-3">
                <div class="image-content">
                  <% if sponsor.logo.present? %>
                    <%= image_tag(serve_image_path(sponsor.logo)) %>
                  <% else %>
                    No Logo
                  <% end %>
                </div>
              </div>
              <div class="caption-name">
                <%= sponsor.name %>
              </div>
              <div class="caption-type">
                <%= sponsor.type %>
              </div>
              <div class="caption-type">
                <% if sponsor.link.blank?  %>
                  No Link
                <% else %>
                  <%= link_to(sponsor.link, url_with_default_protocol(sponsor.link), target: '_blank') %>
                <% end %>
              </div>
              <div class="button">
                <%= button_to('Show', admin_event_sponsor_path(@event.year, sponsor), method: "get", class: "btn btn-info") %>
              </div>
              <div class="button">
                <%= button_to('Edit', edit_admin_event_sponsor_path(@event.year, sponsor), method: "get", class: "btn btn-info") %>
              </div>
              <div class="button">
                <%= button_to('Destroy', admin_event_sponsor_path(@event.year, sponsor),
                    method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/sponsors/new.html.erb
<section id="admin-form" class="section-container">
  <div class="row">
    <div class="title">
      New Sponsor for NUANSA <%= @event.year %>
    </div>
    <div class="content">
      <%= render 'form', sponsor: @sponsor, target_url: admin_event_sponsors_path %>

      <br><br>
      
      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-4">
          <%= button_to("Event Menu", admin_events_path, method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-4">
          <%= button_to("Show Event", admin_event_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-4">
          <%= button_to('Sponsors', admin_event_sponsors_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/sponsors/show.html.erb
<section id="admin-show" class="section-container">
  <div class="row">
    <div class="title">
      Sponsor for NUANSA <%= @event.year %>
    </div>
    <div class="content">
      <div class="info-fields">
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Sponsorship Type</div>
          <div class="col-lg-10 col-md-12 field-value"><%= @sponsor.type %></div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Sponsor Name</div>
          <div class="col-lg-10 col-md-12 field-value"><%= @sponsor.name %></div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Sponsor Link</div>
          <div class="col-lg-10 col-md-12 field-value">
            <% if @sponsor.link.blank?  %>
              No Link
            <% else %>
              <%= link_to(@sponsor.link, url_with_default_protocol(@sponsor.link), target: '_blank') %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-2 col-md-12 field-key">Logo</div>
          <div class="col-lg-10 col-md-12 field-value">
            <%= @sponsor.logo.present? ? image_tag(serve_image_path(@sponsor.logo), height: '100px') : 'NO LOGO' %>
          </div>
        </div>
      </div>

      <br><br>

      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-3 col-md-3 col-xs-6">
          <%= button_to('Event Menu', admin_events_path, method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-3 col-md-3 col-xs-6">
          <%= button_to('Show Event', admin_event_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-3 col-md-3 col-xs-6">
          <%= button_to('Back to Sponsors', admin_event_sponsors_path(@event.year), method: "get", class: "btn btn-info") %>
        </div>
        <div class="col-lg-3 col-md-3 col-xs-6">
          <%= button_to("Edit", edit_admin_event_sponsor_path(@event.year, @sponsor), method: "get", class: "btn btn-info") %>
        </div>
      </div>
    </div>
  </div>
</section>