config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # rubocop:todo Metrics/BlockLength
  root 'welcome#index'

  get 'image/:id/serve', to: 'images#serve', as: :serve_image
  get 'e-booklet', to: 'welcome#serve_booklet', as: :serve_booklet

  resources :gallery_photos, only: :index

  resources :event_previews, only: :index

  devise_scope :user do
    get '/sign_up' => 'users/registrations#new', as: :new_user_registration

    get '/login' => 'users/sessions#new', as: :new_user_session
    post '/login' => 'users/sessions#create', as: :user_session
    delete '/logout' => 'users/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users,
             skip: %i[sessions],
             controllers: {
               passwords: 'users/passwords',
               registrations: 'users/registrations',
               confirmations: 'users/confirmations',
               omniauth_callbacks: 'users/omniauth_callbacks'
             }

  resources :events, only: %i[index show], param: :year do
    get 'load_photos',
        to: 'events#load_photos',
        as: :load_photos,
        constraints: ->(req) { req.format == :js }
  end

  get '/ticket/claim', to: 'tickets#claim', as: 'claim_ticket'
  post '/tickets/synchronize', to: 'tickets#synchronize'

  get '/sold_out_night', to: 'welcome#sold_out_night', as: 'sold_out_night'
  get '/sold_out_matinee',
      to: 'welcome#sold_out_matinee', as: 'sold_out_matinee'
  get '/buy_special', to: 'welcome#buy_special', as: 'buy_special'
  get '/donation', to: 'welcome#donation', as: 'donation'

  namespace :admin do
    root 'admin#index'

    resources :users, except: %i[new create]
    resources :frequently_asked_questions, except: :show
    resources :testimonies

    resources :events, param: 'year' do
      resources :sponsors
      resources :gallery_photos, only: %i[index new create destroy]
      resources :event_previews
    end

    resources :tickets, only: %i[create new index show destroy]
    get '/ticket/claim', to: 'tickets#claim', as: 'claim_ticket'
    post '/ticket/claim', to: 'tickets#redeem', as: nil
    post '/ticket/confirmation_email/:id',
         to: 'tickets#send_confirmation_email', as: 'ticket_email_confirmation'
    post '/tickets/clear_mock_tickets',
         to: 'tickets#clear_mock_tickets', as: 'clear_mock_tickets'

    resources :subscribers, only: %i[index destroy]
    get 'subscribers/write_email',
        to: 'subscribers#write_email', as: :write_email
    post 'subscribers/send_email', to: 'subscribers#send_email', as: :send_email
    get 'subscribers/confirm_email_sent',
        to: 'subscribers#confirm_email_sent', as: :confirm_email_sent
    get 'subscribers/sync_with_customer',
        to: 'subscribers#sync_with_customer', as: :sync_with_customer
  end

  get '/unsubscribe', to: 'admin/subscribers#unsubscribe', as: :unsubscribe
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  has_secure_token :claim_token

  belongs_to :customer, inverse_of: :tickets

  has_many :claim_histories, dependent: :destroy, inverse_of: :ticket

  before_validation :titleize_name

  def total_claimed
    claim_histories.sum('claim_quantity')
  end

  def total_unclaimed
    quantity - total_claimed
  end

  def send_confirmation_email
    ApplicationMailer.with(ticket: self).ticket_confirmation.deliver_now
    self.last_confirmation_email = DateTime.now
    save
  end

  private

  def titleize_name
    self.name = name.titleize
  end
end

app/controllers/admin/tickets_controller.rb
# frozen_string_literal: true

module Admin
  class TicketsController < ApplicationController
    before_action :ensure_admin
    before_action :ensure_superuser,
                  only: %i[destroy new create send_confirmation_email]

    def index
      @tickets = Ticket.includes(:customer).order(:purchased_at)
    end

    def show
      @ticket = Ticket.includes(:customer).find(params[:id])
    rescue StandardError
      not_found
    end

    def new
      @ticket = Ticket.new
    end

    def create
      new_ticket = create_ticket_from_mock_data(mock_ticket_params)
      new_ticket.send_confirmation_email

      flash[:notice] = 'Ticket has been created!!!'
      redirect_to admin_ticket_url(new_ticket)
    rescue StandardError
      not_found
    end

    def claim
      @ticket = Ticket.find_by!(claim_token: params['claim_token'])
    rescue StandardError
      not_found
    end

    # rubocop:todo Metrics/MethodLength
    def redeem
      @ticket = Ticket.find_by!(claim_token: params[:claim_token])
      total_claim = params[:quantity]

      @ticket.claim_histories.create!(
        claimed_by: current_user.username,
        claimed_at: DateTime.now,
        claim_quantity: total_claim
      )

      redirect_to admin_claim_ticket_url(claim_token: @ticket.claim_token),
                  notice:
                    'You are claiming for' \
                      " #{total_claim} #{'people'.pluralize(total_claim)}"
    rescue StandardError
      redirect_to admin_claim_ticket_url(claim_token: @ticket.claim_token),
                  flash: {
                    popup_alert: 'There is an error in claiming the ticket.'
                  }
    end
    # rubocop:enable Metrics/MethodLength

    def destroy
      @ticket = Ticket.find(params[:id])
      @ticket.destroy
      redirect_to admin_tickets_url,
                  notice: 'Ticket was successfully destroyed.'
    end

    def clear_mock_tickets
      Ticket.where(ticket_type: 'MOCK').destroy_all
      redirect_to admin_tickets_url,
                  notice: 'All mock tickets have been successfully destroyed.'
    rescue StandardError
      redirect_to admin_tickets_url,
                  flash: { popup_alert: 'Failed to destroy all mock tickets.' }
    end

    def send_confirmation_email
      @ticket = Ticket.find(params[:id])
      @ticket.send_confirmation_email
      redirect_to admin_tickets_url,
                  notice: 'Confirmation ticket has been sent.'
    rescue StandardError
      redirect_to admin_tickets_url,
                  flash: {
                    popup_alert: 'Confirmation email failed to be sent.'
                  }
    end

    private

    def mock_ticket_params
      params.require(:ticket).permit(:name, :email, :quantity)
    end

    # rubocop:todo Metrics/MethodLength
    def create_ticket_from_mock_data(ticket_info)
      customer =
        Customer.find_or_create_by!(email: ticket_info[:email].downcase)
      ticket = nil
      5.times do |index|
        ticket =
          customer.tickets.create!(
            booking_reference: SecureRandom.base58(5),
            ticket_type: 'MOCK',
            name: ticket_info[:name],
            quantity: ticket_info[:quantity],
            purchased_at: DateTime.now
          )
        break
      rescue StandardError
        raise if index == 4
      end

      ticket
    end
    # rubocop:enable Metrics/MethodLength # rubocop:todo Metrics/AbcSize # rubocop:todo Metrics/AbcSize
  end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :synchronize

  def claim
    ensure_admin
    return if performed?

    redirect_to admin_claim_ticket_path(claim_token: params[:claim_token])
  end

  def synchronize
    not_found && return unless params[:sync_token] == ENV['TICKET_SYNC_TOKEN']

    tickets = []
    ActiveRecord::Base.transaction do
      new_transactions = fetch_new_transactions
      new_transactions.each do |transaction|
        new_ticket = create_ticket_from_transaction(transaction)
        tickets.push(new_ticket)
      end
    end

    send_confirmation_emails(tickets)

    flash[:notice] = 'Tickets have successfully been synchronized!'
    redirect_to root_path
  end

  private

  def fetch_new_transactions
    new_transactions =
      Transaction.where('created_at > ?', LastTransaction.first.time)

    unless new_transactions.empty?
      LastTransaction.update_all(time: new_transactions.maximum('created_at'))
    end

    new_transactions
  end

  # rubocop:todo Metrics/MethodLength
  def create_ticket_from_transaction(transaction)
    customer = Customer.find_or_create_by!(email: transaction.email.downcase)
    ticket = nil
    5.times do |index|
      ticket =
        customer.tickets.create!(
          booking_reference: transaction.booking_reference,
          ticket_type: transaction.ticket_type,
          name: transaction.name,
          quantity: transaction.quantity,
          purchased_at: transaction.purchased_at
        )
      break
    rescue StandardError
      raise if index == 4
    end

    ticket
  end
  # rubocop:enable Metrics/MethodLength

  def send_confirmation_emails(tickets)
    tickets.each(&:send_confirmation_email)
  end # rubocop:todo Metrics/MethodLength
end

app/helpers/admin/tickets_helper.rb
# frozen_string_literal: true

module Admin::TicketsHelper; end

app/helpers/tickets_helper.rb
# frozen_string_literal: true

module TicketsHelper; end

app/views/admin/tickets/_mock_form.html.erb
<%= form_with(model: ticket, local: true, url: admin_tickets_path) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited the ticket from being created:</h2>
      <ul>
      <% ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-fields">

    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :name, "Name" %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.text_field :name, required: true %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :email, "Email" %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.text_field :email, required: true %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">
        <%= form.label :quantiy, "Quantity" %>
      </div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= form.number_field :quantity, min: 1, max: 20, required: true %>
      </div>
    </div>
      
    <div class="row">
      <div class="col-lg-12">
        <%= form.submit 'Submit', class: "submit-button" %>      
      </div>
    </div>
    
  </div>
<% end %>

app/views/admin/tickets/_ticket_details.html.erb
<div class="info-fields">
  <div class="row">
    <div class="col-lg-12"></div>
    <div class="col-lg-2 col-md-12 field-key">Name</div>
    <div class="col-lg-10 col-md-12 field-value">
      <%= ticket.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12"></div>
    <div class="col-lg-2 col-md-12 field-key">Email</div>
    <div class="col-lg-10 col-md-12 field-value">
      <%= ticket.customer ? ticket.customer.email : 'Customer has been deleted' %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12"></div>
    <div class="col-lg-2 col-md-12 field-key">Booking Reference</div>
    <div class="col-lg-10 col-md-12 field-value">
      <%= ticket.booking_reference %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12"></div>
    <div class="col-lg-2 col-md-12 field-key">Ticket Type</div>
    <div class="col-lg-10 col-md-12 field-value">
      <%= ticket.ticket_type %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12"></div>
    <div class="col-lg-2 col-md-12 field-key">Date Purchased</div>
    <div class="col-lg-10 col-md-12 field-value">
      <%= ticket.purchased_at.getlocal %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12"></div>
    <div class="col-lg-2 col-md-12 field-key">Quantity</div>
    <div class="col-lg-10 col-md-12 field-value">
      <%= ticket.quantity %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12"></div>
    <div class="col-lg-2 col-md-12 field-key">Total Claimed</div>
    <div class="col-lg-10 col-md-12 field-value">
      <%= ticket.total_claimed %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12"></div>
    <div class="col-lg-2 col-md-12 field-key">Total Unclaimed</div>
    <div class="col-lg-10 col-md-12 field-value">
      <%= ticket.total_unclaimed %>
    </div>
  </div>
  <% if current_user.has_role?(:superuser) && local_assigns[:show_token] %>
    <div class="row">
      <div class="col-lg-12"></div>
      <div class="col-lg-2 col-md-12 field-key">Claim Token</div>
      <div class="col-lg-10 col-md-12 field-value">
        <%= ticket.claim_token %>
      </div>
    </div>
  <% end %>
</div>

<% if ticket.claim_histories.count != 0 %>
  <center> <h1> Ticket claim history </h1> </center>
  <div class="info-fields">
    <% ticket.claim_histories.each_with_index do |history, idx| %>
      <div class="row">
        <div class="col-lg-12"></div>
        <div class="col-lg-3 col-md-12 field-key">No <%= idx + 1 %>.</div>
        <div class="col-lg-3 col-md-12 field-key"><%= history.claimed_by %></div>
        <div class="col-lg-3 col-md-12 field-key"><%= history.claimed_at.getlocal %></div>
        <div class="col-lg-3 col-md-12 field-key"><%= history.claim_quantity %></div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/admin/tickets/claim.html.erb
<section id="admin-ticket-claim" class="section-container">
  <div class="row">
    <div class="title">
      Ticket Claim
    </div>

    <div class="content">
      <div class="info-fields">
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-4 col-md-6 field-key">Name</div>
          <div class="col-lg-8 col-md-6 field-value">
            <%= @ticket.name %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-4 col-md-6 field-key">Email</div>
          <div class="col-lg-8 col-md-6 field-value">
            <%= @ticket.customer ? @ticket.customer.email : 'Customer has been deleted' %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-4 col-md-6 field-key">Booking Reference</div>
          <div class="col-lg-8 col-md-6 field-value">
            <%= @ticket.booking_reference %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-4 col-md-6 field-key">Ticket Type</div>
          <div class="col-lg-8 col-md-6 field-value">
            <%= @ticket.ticket_type %>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12"></div>
          <div class="col-lg-4 col-md-6 field-key">Claimable Quantity</div>
          <div class="col-lg-8 col-md-6 field-value">
            <%= @ticket.total_unclaimed %> / <%= @ticket.quantity %>
          </div>
        </div>
      </div>

      <br>

      <div class="row">
        <div class="col-lg-12 col-md-12 col-xs-12">
          <%= form_with(url: admin_claim_ticket_path, method: :post) do %>
            <%= hidden_field_tag(:claim_token, @ticket.claim_token) %>
            <% if @ticket.total_unclaimed <= 0 %>
              All tickets have been claimed.
            <% else %>
              <%= label_tag(:quantity, "Total claim") %>            
              <%= number_field_tag(:quantity, 1, in: 1..@ticket.total_unclaimed) %>
              <%= submit_tag("Claim Ticket", class: "btn btn-info", data: {confirm: "Do you want to claim this ticket?"}) %>
            <% end %>
          <% end %>
        </div>
      </div>

      <% if @ticket.claim_histories.count != 0 %>
        <center> <h1> Ticket claim history </h1> </center>
        <div class="info-fields">
          <% @ticket.claim_histories.each_with_index do |history, idx| %>
            <div class="row">
              <div class="col-lg-12"></div>
              <div class="col-lg-4 col-md-12 field-key"><%= history.claimed_by %></div>
              <div class="col-lg-4 col-md-12 field-key"><%= history.claimed_at.getlocal %></div>
              <div class="col-lg-4 col-md-12 field-key"><%= history.claim_quantity %></div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/tickets/index.html.erb
<section id="admin-tickets-index" class="section-container">
  <div class="row">
    <div class="title">
      Ticket List
    </div>
    <div class="content">
      <div class="col-lg-12">
        <% @tickets.each do |ticket| %>
          <div class="row info-fields">
            <div class="col-lg-12"></div>
            <div class="col-lg-2 col-md-12 col-xs-12 info-item">
              <%= ticket.name %>
            </div>
            <div class="col-lg-1 col-md-12 col-xs-12 info-item">
              <%= ticket.booking_reference %>
            </div>
            <div class="col-lg-1 col-md-12 col-xs-12 info-item">
              <%= ticket.ticket_type %>
            </div>
            <div class="col-lg-1 col-md-12 col-xs-12 info-item">
              <%= ticket.quantity %>
            </div>

            <div class="col-lg-1 col-md-12 col-xs-12 info-item">
              <%= button_to("Show", admin_ticket_path(ticket), method: :get, class: "btn btn-info") %>
            </div>

            <% if current_user.has_role? :superuser %>
              <div class="col-lg-4 col-md-12 col-xs-12 info-item">
                <%= button_to("Send Email Confirmation", admin_ticket_email_confirmation_path(ticket), method: :post, class: "btn btn-info",
                  data: { confirm: 'Do you want to send this ticket confirmation email?' }) %>
                <br> Last:
                <% if ticket.last_confirmation_email %>
                  <%= ticket.last_confirmation_email.getlocal %>
                <% else %>
                  Not yet sent
                <% end %>
              </div>
              
              <div class="col-lg-1 col-md-12 col-xs-12 info-item">
                <%= button_to("Claim Page", admin_claim_ticket_path, params: { claim_token:
                  ticket.claim_token }, class: "btn btn-info", method: :get) %>
              </div>

              <div class="col-lg-1 col-md-12 col-xs-12 info-item">
                <%= button_to "Delete", admin_ticket_path(ticket), method: :delete, data:
                  { confirm: 'Do you want to delete this ticket?' }, class: "btn btn-info" %>
              </div>
            <% end %>
          </div>
        <% end %>

        <br><br>

        <div class="row">
          <div class="col-lg-12"></div>
          <% if current_user.has_role?(:superuser) %>
            <div class="col-lg-4">
              <%= button_to("Back", admin_root_path, method: "get", class: "btn btn-info") %>
            </div>
            <div class="col-lg-4">
              <%= button_to("Create Mock Ticket", new_admin_ticket_path, method: "get", class: "btn btn-info") %>
            </div>
            <div class="col-lg-4">
              <%= button_to("Clear Mock Tickets", admin_clear_mock_tickets_path, method: "post", class: "btn btn-info") %>
            </div>
          <% else %>
            <div class="col-lg-12">
              <%= button_to("Back", admin_root_path, method: "get", class: "btn btn-info") %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/tickets/new.html.erb
<section id="admin-ticket-show" class="section-container">
  <div class="row">
    <div class="title">
      Ticket Show
    </div>

    <div class="content">
      <div id="admin-form">
        <%= render "mock_form", ticket: @ticket %>
      </div>
      
      <br><br>

      <div class="row">
        <div class="col-lg-12 col-md-12 col-xs-12">
          <%= button_to("Back to Tickets", admin_tickets_path, method: :get, class: "btn btn-info") %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/tickets/show.html.erb
<section id="admin-ticket-show" class="section-container">
  <div class="row">
    <div class="title">
      Ticket Show
    </div>

    <div class="content">
      <%= render "ticket_details", ticket: @ticket, show_token: true %>

      <br><br>

      <div class="row">
        <div class="col-lg-12 col-md-12 col-xs-12">
          <%= button_to("Back to Tickets", admin_tickets_path, method: :get, class: "btn btn-info") %>
        </div>
      </div>
    </div>
  </div>
</section>